#!/usr/bin/env python3
"""Map USLS course codes to college slugs and emit catalog_subjects INSERT SQL."""

import csv
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CSV_PATH = ROOT / "data" / "usls_catalog_subjects.csv"
OUT_PATH = ROOT / "migrations" / "20260331140000_usls_registrar_catalog_subjects.sql"

# First matching regex wins. Order matters.
RULES: list[tuple[str, str]] = [
    # Nursing
    (r"^NCM", "nursing"),
    (r"^INA2$", "nursing"),
    (r"^MC3$", "nursing"),
    # Tourism & hospitality
    (r"^CTH", "tourism"),
    (r"^ETM", "tourism"),
    (r"^ETOUR", "tourism"),
    (r"^HML", "tourism"),
    (r"^HMP", "tourism"),
    (r"^PHM", "tourism"),
    (r"^TML", "tourism"),
    (r"^TMP", "tourism"),
    (r"^HTC", "tourism"),
    (r"^HTB", "tourism"),
    (r"^FTECH", "tourism"),
    (r"^ECULIN", "tourism"),
    (r"^HMPRAC", "tourism"),
    (r"^TMPRAC", "tourism"),
    (r"^PTM", "tourism"),
    # Engineering (incl. ChE, EE, ECE, CpE, materials, GE)
    (r"^ECHE", "engineering"),
    (r"^EECE", "engineering"),
    (r"^EELEC", "engineering"),
    (r"^EIA", "engineering"),
    (r"^EMA\d", "engineering"),
    (r"^EE\d", "engineering"),
    (r"^GE10", "engineering"),
    (r"^GE11", "engineering"),
    (r"^GE20", "engineering"),
    (r"^PCHEM101C", "engineering"),
    (r"^PHY101E", "engineering"),
    (r"^EMAT", "engineering"),
    (r"^ECPE", "engineering"),
    # Computing & IT / multimedia
    (r"^CC\d", "computing"),
    (r"^CFP", "computing"),
    (r"^CSP", "computing"),
    (r"^CSE", "computing"),
    (r"^CPETE", "computing"),
    (r"^DSTRUC$", "computing"),
    (r"^ITP", "computing"),
    (r"^ITC", "computing"),
    (r"^ITL", "computing"),
    (r"^LITE$", "computing"),
    (r"^PYTHON$", "computing"),
    (r"^SAD$", "computing"),
    (r"^UXUI$", "computing"),
    (r"^PROGR2$", "computing"),
    (r"^INFOM$", "computing"),
    (r"^ENELECT3$", "computing"),
    (r"^3D$", "computing"),
    (r"^EMC", "computing"),
    (r"^EMP", "computing"),
    (r"^EME401$", "computing"),
    # Education
    (r"^ECED", "education"),
    (r"^EDCN", "education"),
    (r"^EDENG", "education"),
    (r"^EED", "education"),
    (r"^MAED", "education"),
    (r"^PHED", "education"),
    (r"^SNED", "education"),
    (r"^SOCED", "education"),
    # College of Business & Accountancy (incl. Agribusiness — per registrar)
    (r"^ACCT", "business"),
    (r"^AIS", "business"),
    (r"^MACC", "business"),
    (r"^BA\d", "business"),
    (r"^BAPRAC", "business"),
    (r"^BLOGIC$", "business"),
    (r"^BMACRO$", "business"),
    (r"^BMGT", "business"),
    (r"^BMICRO$", "business"),
    (r"^BSTAT$", "business"),
    (r"^EBRES", "business"),
    (r"^ECON", "business"),
    (r"^ENTMND$", "business"),
    (r"^ENTRP", "business"),
    (r"^FELECT", "business"),
    (r"^FINMA", "business"),
    (r"^FS100$", "business"),
    (r"^HRMGT$", "business"),
    (r"^IBT100$", "business"),
    (r"^INFOT", "business"),
    (r"^MACRO$", "business"),
    (r"^MBRES", "business"),
    (r"^MRKT", "business"),
    (r"^OBRES", "business"),
    (r"^OMTQM$", "business"),
    (r"^OPM", "business"),
    (r"^PRMGT", "business"),
    (r"^STRAT100$", "business"),
    (r"^TXTN", "business"),
    (r"^COMLAW", "business"),
    (r"^MKEL", "business"),
    (r"^AGR", "business"),  # Agribusiness (CBA)
    (r"^AGRIB", "business"),
    (r"^AGRICPRAC", "business"),
    (r"^LITEB$", "business"),
    # IDST split
    (r"^IDST107$", "business"),
    (r"^IDST108$", "business"),
    (r"^IDST115$", "business"),
    (r"^IDST118$", "business"),
    (r"^IDST123$", "tourism"),
    (r"^IDST", "arts_science"),
]


def college_for(code: str) -> str:
    u = code.strip().upper()
    for pattern, slug in RULES:
        if re.match(pattern, u):
            return slug
    return "arts_science"


def sql_str(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def main() -> None:
    rows: list[tuple[str, str, str]] = []
    with CSV_PATH.open(newline="", encoding="utf-8") as f:
        r = csv.DictReader(f)
        for row in r:
            code = row["code"].strip()
            label = row["label"].strip()
            if not code:
                continue
            rows.append((college_for(code), code, label))

    lines = [
        "-- USLS registrar catalog → public.catalog_subjects",
        "-- Generated by supabase/scripts/generate_usls_catalog_sql.py",
        "-- Maps each course code to a college slug (heuristic). Adjust script if a course lands in the wrong college.",
        "-- Agribusiness (AGR/AGRIB/…) → slug `business` (College of Business & Accountancy).",
        "",
        "insert into public.catalog_subjects (college_id, name, code)",
        "select c.id, v.name, v.code",
        "from public.colleges c",
        "inner join (",
        "  values",
    ]
    value_lines = []
    for slug, code, name in rows:
        value_lines.append(
            f"    ({sql_str(slug)}, {sql_str(name)}, {sql_str(code)})"
        )
    lines.append(",\n".join(value_lines))
    lines.append(") as v(slug, name, code) on c.slug = v.slug")
    lines.append("on conflict (college_id, code) do update set name = excluded.name;")
    lines.append("")

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT_PATH} ({len(rows)} subjects)")


if __name__ == "__main__":
    main()
